# Generated by Django 5.0.1 on 2024-01-15 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_remove_auctionlist_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
