# Generated by Django 5.0.1 on 2024-01-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auctionlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='buy_now_price',
            field=models.IntegerField(default=0),
        ),
    ]
