# Generated by Django 5.0.1 on 2024-01-16 09:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionlist_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='desc',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
