# Generated by Django 5.0.1 on 2024-01-16 09:51

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auctionlist_short_desc_alter_auctionlist_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlist',
            name='bid_watch_list',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='short_desc',
            field=models.TextField(null=True),
        ),
    ]
